Groups:
  1: ""
  2: ""
  3: ""
  4: ""
  5: ""
  6: ""
  7: ""
  8: ""
  9: ""
  10: ""
  11: ""

Tags:
  1: "§4L | §c§n"
  2: "§4A | §c"
  3: "§9M | §b"
  4: "§9D | §b§n"
  5: "§1M | §3"
  6: "§6C | §e§n"
  7: "§1S | §3"
  8: "§6B | §e"
  9: "§6N | §e"
  10: "§9YT | §b"
  11: "§5V | §d"
  default: "§2S | §a"

Chat:
  1: ''
  2: ''
  3: ''
  4: ''
  5: ''
  6: ''
  7: ''
  8: ''
  9: ''
  10: ''
  11: ''
  default: '§aExamplerank : §c&player >> §a'

